const promptfoo = require('promptfoo').default;

class GeminiOpenAiProvider {
  constructor(options) {
    this.config = options.config;
    const baseModel = this.config?.model || 'google:gemini-1.5-pro';
    this.providerId = options.id || `custom-gemini-openai-${baseModel}`;
    this.baseModel = baseModel;
    this.baseProvider = null;
  }

  id() {
    return this.providerId;
  }

  async _ensureProvider() {
    if (!this.baseProvider) {
      const context = {
        options: {
          id: this.providerId,
          config: this.config,
        },
      };

      this.baseProvider = await promptfoo.loadApiProvider(this.baseModel, context);
    }
    return this.baseProvider;
  }

  /**
   * Maps OpenAI format exchange to Google Gemini API format
   * @param {Array} messages - Array of OpenAI format messages
   * @returns {Array|Object} Mapped Google Gemini prompt format
   */
  _mapOpenAiToGoogle(messages) {
    if (!Array.isArray(messages)) return messages;

    const mappedMessages = [];
    const systemInstructionParts = [];

    messages.forEach((msg) => {
      if (msg.role === 'system') {
        if (typeof msg.content === 'string') {
          if (msg.content) systemInstructionParts.push({ text: msg.content });
        } else if (Array.isArray(msg.content)) {
          msg.content.forEach((part) => {
            if (typeof part === 'string') {
              systemInstructionParts.push({ text: part });
            } else if (part && part.type === 'text' && typeof part.text === 'string') {
              systemInstructionParts.push({ text: part.text });
            }
          });
        }
        return;
      }

      // 1. HANDLE TOOL RESPONSES (role: tool) -> Merge consecutive tool outputs
      if (msg.role === 'tool') {
        let responseContent = msg.content;
        try {
          if (typeof responseContent === 'string') {
            responseContent = JSON.parse(responseContent);
          }
        } catch (e) {
          responseContent = { result: msg.content };
        }

        const functionResponsePart = {
          functionResponse: {
            id: msg.tool_call_id ? msg.tool_call_id.replace('_', '-') : 'call-id',
            name: msg.name,
            response: responseContent,
          },
        };

        // Grouping: If the last message in our accumulator is already a 'user' message
        // generated by a tool, merge this part into it instead of creating a new message.
        const lastMapped = mappedMessages[mappedMessages.length - 1];
        if (lastMapped && lastMapped.role === 'user' && lastMapped._isToolGroup) {
          lastMapped.parts.push(functionResponsePart);
        } else {
          mappedMessages.push({
            role: 'user',
            parts: [functionResponsePart],
            _isToolGroup: true, // Temporary flag used for the grouping loop
          });
        }
        return;
      }

      // 2. HANDLE ASSISTANT TOOL CALLS (Parallel or Single)
      if (msg.role === 'assistant' && msg.tool_calls && msg.tool_calls.length > 0) {
        const parts = msg.tool_calls.map((tool, idx) => {
          let args = tool.function.arguments;
          try {
            if (typeof args === 'string') {
              args = JSON.parse(args);
            }
          } catch (e) {
            args = {};
          }

          const callObj = {
            functionCall: {
              id: tool.id ? tool.id.replace('_', '-') : 'call-id',
              name: tool.function.name,
              args: args,
            },
          };

          // Apply 'thoughtSignature' only to the VERY FIRST function call in the parallel array
          if (idx === 0) {
            callObj.thoughtSignature = 'skip_thought_signature_validator';
          }

          return callObj;
        });

        mappedMessages.push({
          role: 'model',
          parts: parts,
        });
        return;
      }

      // 3. HANDLE STANDARD TEXT MESSAGES (User or Assistant text output)
      let googleRole = msg.role === 'assistant' ? 'model' : msg.role;
      if (msg.content) {
        mappedMessages.push({
          role: googleRole,
          parts: [{ text: msg.content }],
        });
      }
    });

    // Clean up the temporary flag before returning the final mapped array
    const cleanedMessages = mappedMessages.map(({ _isToolGroup, ...rest }) => rest);
    if (systemInstructionParts.length === 0) return cleanedMessages;
    if (cleanedMessages.length === 0) {
      return [{ role: 'user', parts: systemInstructionParts }];
    }
    return {
      contents: cleanedMessages,
      system_instruction: { parts: systemInstructionParts },
    };
  }

  /**
   * Maps Google Gemini function calls to OpenAI function call format
   * @param {Array} data - The raw output data array from Gemini
   * @returns {Array} The mapped OpenAI format
   */
  _mapGoogleToOpenAi(data) {
    return data.map((item, index) => {
      if (item.functionCall) {
        return {
          type: 'function',
          index: index,
          // Use existing ID or fallback to an indexed identifier
          id: item.functionCall.id || `call_${index}`,
          function: {
            name: item.functionCall.name,
            // OpenAI expects arguments as a serialized JSON string
            arguments: JSON.stringify(item.functionCall.args),
          },
        };
      }
      // Return the item unchanged if it is not a function call
      return item;
    });
  }

  async callApi(prompt, context, options) {
    // 1. Get the official provider
    const provider = await this._ensureProvider();

    // 2. Map incoming OpenAI payload to Gemini payload if applicable
    let finalPrompt = prompt;
    try {
      const parsedPrompt = typeof prompt === 'string' ? JSON.parse(prompt) : prompt;
      if (Array.isArray(parsedPrompt)) {
        const mappedPrompt = this._mapOpenAiToGoogle(parsedPrompt);
        // Promptfoo providers typically expect a stringified prompt if passed as an object/array
        finalPrompt = typeof prompt === 'string' ? JSON.stringify(mappedPrompt) : mappedPrompt;
      }
    } catch (e) {
      // Prompt is not a valid JSON array or object, leave it untouched (standard string prompt)
    }

    // 3. Delegate the actual API call to the official native provider
    const response = await this.baseProvider.callApi(finalPrompt, context, options);

    // If there's an error or no output, return the response as-is
    if (!response || !response.output) {
      return response;
    }

    try {
      // 4. Extract and parse the raw Google function call data
      const data =
        typeof response.output === 'string' ? JSON.parse(response.output) : response.output;
      if (Array.isArray(data)) {
        // 5. Map Gemini's structure back to OpenAI format
        response.output = this._mapGoogleToOpenAi(data);
      }
    } catch (e) {
      // If parsing fails (e.g., standard text output), safely leave original response untouched
    }
    return response;
  }
}

module.exports = GeminiOpenAiProvider;
